### ISSUE TITLE
Milestone 1 - AgMT RCL

### ISSUE THREAD

**Issue by samuelanthrayose** [friendsofagape/autographa-roadmap#8]
**Sprint 1 - Learning**
- [x] Learn RCL's, ES6, Context API

**Sprint 2 - Project List and Details View**
- [x] Start with Base project
- [x] Project table/List View
- [x] Project Details New/Edit Page

**Sprint 3 - Project List and Details View**
- [x] Left Menu and Page Container
- [x] Set up linting on commit or PR and on save file(vsconfig)
- [x] Top bar
- [x] Project Table Complete
- [x] Project Details Page Complete

**Sprint 4 - Release 1st Milestone**
- [x] Setup auto deploy on commit to Netlify for Testing
- [x] Testing of the Project List and Details View

**Release of 1st Milestone by end of sprint 4**

**Reference Links:** 
Github-Zenhub: https://github.com/Bridgeconn/autographa-mt#zenhub
[AgMT Components Breakup Figma](https://www.figma.com/proto/gl96mqMLs8VynFojkKentx/AgMT-RCL-Compoents-Breakup?node-id=1%3A2&scaling=min-zoom&page-id=0%3A1)

**Comment by samuelanthrayose** [comment]
Final PR review and testing is pending. It will be completed this week.
