### ISSUE TITLE
Milestone 2 - AgMT RCL

### ISSUE THREAD

**Issue by samuelanthrayose** [friendsofagape/autographa-roadmap#9]
**Sprint 4 - Project Details View** 
- [ ] Book drop Down 
- [ ] Token Panel 
- [ ] Menu Bar
- [ ] Sources Reference Panel

**Sprint 5 - Project Details View**
- [ ] Token Edit 
- [ ] Project Status Bar
- [ ] Occurrences Panel
- [ ] Translation Word Panel
- [ ] Integrate Book/Chapter drop down

**Sprint 6 - Project Details View & Draft Page**
- [ ] Project View Menu
- [ ] Draft Container
- [ ] Draft Menu Bar
- [ ] Draft view panel
- [ ] Print Draft Button

**Sprint 7 & 8 - Release of 2nd Milestone** 
- [ ] Testing of the Project Details View and Draft Page 

**Release of 2nd Milestone by end of sprint 8**

**Reference Links:** 
Github-Zenhub: https://github.com/Bridgeconn/autographa-mt#zenhub
[AgMT Components Breakup Figma](https://www.figma.com/proto/gl96mqMLs8VynFojkKentx/AgMT-RCL-Compoents-Breakup?node-id=1%3A2&scaling=min-zoom&page-id=0%3A1)
